'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),board=document.createElement('canvas'),arena=document.querySelector('.arena');board.width=500;board.height=350;
let bridge,ready=false,stopped=false,last=0,accumulator=0,selectedStartLevel=1,keymap={37:37,39:39,90:90,32:32,88:88},saved=localStorage.getItem('ship10-save'),messageTimer,blurPaused=false;
const held=new Set(),modalPause=new WeakMap();
function present(){const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(board,0,0,canvas.width,canvas.height);}
function fitCanvas(){const r=arena.getBoundingClientRect(),scale=Math.max(.001,Math.min(r.width/500,r.height/350)),w=500*scale,h=350*scale,dpr=devicePixelRatio||1;canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.width=Math.max(1,Math.round(w*dpr));canvas.height=Math.max(1,Math.round(h*dpr));present();}
new ResizeObserver(fitCanvas).observe(arena);
function message(s){$('message').textContent=s;clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('message').textContent='',5000);}
function fail(e){stopped=true;$('error').hidden=false;$('error').textContent='游戏运行错误：'+e.message;console.error(e);}
function refresh(){const s=bridge.state();$('status').textContent=s.paused?'游戏暂停':`${bridge.tuning.config.enabled?'自定义 · ':''}机会 ${s.lives}　得分 ${s.score}　炸弹 ${s.bombs}/${s.capacity}${bridge.tuning.config.enabled&&bridge.tuning.config.invincible?'　持续无敌':''}`;$('level').textContent=`第 ${s.level} 关`;$('pause').textContent=s.paused?'继续 F3':'暂停 F3';$('sound').textContent=bridge.sound?'音效 F5':'音效关闭 F5';$('load').disabled=!saved;if(bridge.notice){message(bridge.notice);bridge.notice='';}}
function action(fn){if(!ready||bridge.cpu.suspended)return;try{fn();refresh();present();}catch(e){fail(e);}}
function down(k){action(()=>{if(k===113){bridge.startLevel(selectedStartLevel);stopped=false;$('error').hidden=true;last=0;accumulator=0;if(bridge.state().paused)bridge.keyDown(114);}else if(k===116){bridge.sound=!bridge.sound;if(!bridge.sound)bridge.stopAudio();}else bridge.keyDown(k);});}
function up(k){if(ready&&!bridge.cpu.suspended)action(()=>bridge.keyUp(k));}
function releaseKeys(){for(const k of held)up(k);held.clear();}
function enableAudio(){if(ready)bridge.audioReady().catch(()=>{});}
function openDialog(id){if(!ready||document.querySelector('dialog[open]'))return;releaseKeys();const d=$(id),running=!bridge.state().paused;modalPause.set(d,running);if(running)down(114);d.showModal();}
for(const d of document.querySelectorAll('dialog'))d.addEventListener('close',()=>{if(modalPause.get(d)&&bridge.state().paused)down(114);modalPause.delete(d);last=0;accumulator=0;canvas.focus();});
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
$('start').onclick=()=>{down(113);enableAudio();canvas.focus();};$('pause').onclick=()=>{releaseKeys();down(114);canvas.focus();};$('sound').onclick=()=>{down(116);enableAudio();};$('help').onclick=()=>openDialog('instructions');$('closeHelp').onclick=()=>$('instructions').close();$('quit').onclick=()=>action(()=>{releaseKeys();bridge.end();});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('app').requestFullscreen();}catch{message('此浏览器暂不支持全屏');}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'退出全屏':'全屏';fitCanvas();});
function storeSave(){const bytes=ShipSave.capture(bridge);saved=new TextDecoder().decode(bytes);localStorage.setItem('ship10-save',saved);return bytes;}
function restoreSave(bytes){ShipSave.restore(bridge,ShipSave.decode(bytes));stopped=false;last=0;accumulator=0;saveSettings();}
$('save').onclick=()=>action(()=>{storeSave();message('存档已保存到此浏览器');});$('load').onclick=()=>action(()=>{if(saved){restoreSave(new TextEncoder().encode(saved));message('已读取存档');}});
function keyName(k){return ({32:'Space',37:'←',39:'→',13:'Enter'})[k]||String.fromCharCode(k);}
for(let i=1;i<=20;i++)$('startLevel').add(new Option('第 '+i+' 关',i));for(const step of [1,21,41,61,81,101,121,141,161,181])$('speed').add(new Option(step+' 毫秒 / 帧',step));
function fillRules(r){$('customRules').checked=r.enabled;$('invincible').checked=r.invincible;for(const f of document.querySelectorAll('[data-rule]'))f.value=r[f.dataset.rule];$('tuningFields').disabled=!r.enabled;}
$('customRules').onchange=()=>$('tuningFields').disabled=!$('customRules').checked;$('resetRules').onclick=()=>fillRules(ShipTuning.defaults);
function settingsError(s){$('optionsError').textContent=s;$('optionsError').hidden=false;}
$('settings').onclick=()=>{if(!ready)return;fillRules(bridge.tuning.config);$('optionsError').hidden=true;$('startLevel').value=selectedStartLevel;$('speed').value=bridge.step;$('useMouse').checked=bridge.useMouse;$('playerName').value=bridge.playerName||'Player';for(const f of document.querySelectorAll('[data-keymap]')){f.dataset.key=keymap[f.dataset.keymap];f.value=keyName(+f.dataset.key);}openDialog('options');};
for(const f of document.querySelectorAll('[data-keymap]'))f.onkeydown=e=>{if(e.key==='Tab'||e.key==='Escape')return;e.preventDefault();if(e.keyCode<32||e.keyCode>=112){settingsError('请选择方向键、空格、字母或数字键');return;}f.dataset.key=e.keyCode;f.value=keyName(e.keyCode);};
function saveSettings(){localStorage.setItem('ship10-settings',JSON.stringify({startLevel:selectedStartLevel,step:bridge.step,mouse:bridge.useMouse,sound:bridge.sound,name:bridge.playerName,gameplay:bridge.tuning.config,keymap}));}
function applySettings(){const rules={enabled:$('customRules').checked,invincible:$('invincible').checked};for(const f of document.querySelectorAll('[data-rule]')){if(rules.enabled&&!f.reportValidity())return false;rules[f.dataset.rule]=Number(f.value);}const keys=[...document.querySelectorAll('[data-keymap]')];if(new Set(keys.map(f=>+f.dataset.key)).size!==keys.length){settingsError('各操作的键位不能重复');return false;}try{ShipTuning.rules(rules);}catch(e){settingsError(e.message);return false;}selectedStartLevel=+$('startLevel').value;bridge.tuning.rescaleProtection(bridge.step,+$('speed').value);bridge.step=+$('speed').value;bridge.tuning.apply(rules);bridge.useMouse=$('useMouse').checked;bridge.playerName=$('playerName').value.trim()||'Player';for(const f of keys)keymap[f.dataset.keymap]=+f.dataset.key;saveSettings();$('optionsError').hidden=true;return true;}
$('applySettings').onclick=()=>action(()=>{if(applySettings()){$('options').close();message('设置已应用');}});$('startSelected').onclick=()=>action(()=>{if(!applySettings())return;bridge.startLevel(selectedStartLevel);if(bridge.state().paused)bridge.keyDown(114);modalPause.set($('options'),false);$('options').close();last=0;accumulator=0;});
function showScores(){const c=bridge.cpu,base=c.read(bridge.game+0x14c),rows=$('scoreRows');rows.replaceChildren();for(let i=0;i<10;i++){const a=base+i*40,tr=document.createElement('tr');for(const value of [i+1,bridge.str(a+4)||'—',c.read(a+24),c.read(a+20),bridge.str(a+28)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}rows.append(tr);}openDialog('heroes');}
$('scores').onclick=()=>action(showScores);
function showNameEntry(){if($('scoreEntry').open)return;held.clear();$('entryScore').textContent=bridge.state().score;$('entryName').value=bridge.playerName&&bridge.playerName!=='Player'?bridge.playerName:'';$('entryError').hidden=true;$('scoreEntry').showModal();$('entryName').focus();}
function finishName(name){try{bridge.completeName(name);for(const k of [37,39])bridge.keyUp(k);last=0;accumulator=0;$('scoreEntry').close();refresh();if(bridge.showScores){bridge.showScores=false;showScores();}}catch(e){fail(e);}}
$('entryForm').onsubmit=e=>{e.preventDefault();const name=$('entryName').value.trim();if(!name||bridge.decoder.decode(bridge.nameBytes(name))!==name){$('entryError').textContent='请输入名字，最多 6 个汉字或 12 个字母。';$('entryError').hidden=false;return;}finishName(name);saveSettings();};$('cancelEntry').onclick=()=>finishName(null);$('scoreEntry').addEventListener('cancel',e=>{e.preventDefault();finishName(null);});
$('exportSave').onclick=()=>action(()=>{const bytes=storeSave(),url=URL.createObjectURL(new Blob([bytes])),a=document.createElement('a');a.href=url;a.download='潜艇大战V1.0.ship10';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('存档已导出');});$('importSave').onclick=()=>$('saveFile').click();$('saveFile').onchange=async()=>{const f=$('saveFile').files[0];if(!f)return;try{const bytes=new Uint8Array(await f.arrayBuffer());ShipSave.decode(bytes);action(()=>{restoreSave(bytes);saved=new TextDecoder().decode(bytes);localStorage.setItem('ship10-save',saved);modalPause.set($('options'),false);$('options').close();message('存档已导入');});}catch(e){settingsError(e.message);}$('saveFile').value='';};
function nativeKey(k){return +Object.keys(keymap).find(original=>keymap[original]===k)||k;}
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;const k=e.keyCode;if(e.ctrlKey){const id={83:'save',76:'load'}[k];if(id){e.preventDefault();$(id).click();}else if(k===77){e.preventDefault();action(()=>{bridge.useMouse=!bridge.useMouse;saveSettings();});}return;}if(e.altKey||e.metaKey)return;const id={112:'help',115:'settings',119:'fullscreen',120:'scores',27:'quit'}[k];if(id){e.preventDefault();if(!e.repeat)$(id).click();return;}if([113,114,116].includes(k)){e.preventDefault();if(!e.repeat)down(k);return;}const n=nativeKey(k);if([32,37,39,90,88].includes(n)){e.preventDefault();held.add(n);down(n);enableAudio();}});document.addEventListener('keyup',e=>{const n=nativeKey(e.keyCode);held.delete(n);up(n);});
window.addEventListener('blur',()=>{releaseKeys();blurPaused=ready&&!bridge.state().paused&&!document.querySelector('dialog[open]');if(blurPaused)down(114);last=0;accumulator=0;});window.addEventListener('focus',()=>{if(blurPaused&&bridge.state().paused)down(114);blurPaused=false;last=0;accumulator=0;});
for(const b of document.querySelectorAll('[data-key]')){let timer;const k=+b.dataset.key;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.add(k);down(k);if([32,90,88].includes(k))timer=setInterval(()=>down(k),150);enableAudio();};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{clearInterval(timer);held.delete(k);up(k);};}
function pointer(e,click){if(!ready||document.querySelector('dialog[open]'))return;const r=canvas.getBoundingClientRect();action(()=>bridge.mouse((e.clientX-r.left)*500/r.width,(e.clientY-r.top)*350/r.height,click));if(click)enableAudio();}
canvas.onpointermove=e=>{if(e.pointerType==='mouse')pointer(e,false);};canvas.onpointerdown=e=>{e.preventDefault();canvas.focus();pointer(e,true);};canvas.oncontextmenu=e=>e.preventDefault();
function loop(t){if(ready&&bridge.pendingName){showNameEntry();last=t;accumulator=0;requestAnimationFrame(loop);return;}if(ready&&!stopped){accumulator+=last?Math.min(t-last,120):0;try{let updated=false,steps=0;while(accumulator>=bridge.step&&steps++<24){bridge.frame();accumulator-=bridge.step;updated=true;if(bridge.cpu.suspended)break;}if(updated)present();refresh();if(bridge.pendingName)showNameEntry();}catch(e){fail(e);}}last=t;requestAnimationFrame(loop);}
(async()=>{try{const images={};await Promise.all(SHIP_RESOURCES.images.map(id=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[id]=im;resolve();};im.onerror=()=>reject(Error('图片加载失败 '+id));im.src=SHIP_RESOURCES.data[id];})));bridge=new ShipBridge(new ShipCPU(SHIP_MACHINE),board,images);window.ship=bridge;bridge.initialize();bridge.useMouse=true;const cfg=JSON.parse(localStorage.getItem('ship10-settings')||'null');if(cfg){bridge.playerName=cfg.name;bridge.useMouse=!!cfg.mouse;bridge.sound=cfg.sound!==false;if(Number.isFinite(cfg.step)&&cfg.step>=1&&cfg.step<=181)bridge.step=cfg.step;if(cfg.gameplay)bridge.tuning.apply(cfg.gameplay);if(cfg.keymap)keymap=cfg.keymap;if(Number.isInteger(cfg.startLevel)&&cfg.startLevel>=1&&cfg.startLevel<=20)selectedStartLevel=cfg.startLevel;bridge.startLevel(selectedStartLevel);}ready=true;window.gameReady=true;fitCanvas();refresh();requestAnimationFrame(loop);}catch(e){fail(e);}})();
