/* Browser-only snapshots. V1.0 has no native progress file format. */
'use strict';
class ShipSave {
 static encode(b){return btoa(Array.from(b,x=>String.fromCharCode(x)).join(''));}
 static capture(b){const c=b.cpu;return new TextEncoder().encode(JSON.stringify({format:'ship10-web',version:1,source:'03756e0340b608bff99b889b351ff1d61397f4b62a3a830476845c59ed357d3b',step:b.step,rules:b.tuning.config,protectionKind:b.tuning.protectionKind,seed:c.seed,heap:c.heap,blocks:[...c.blocks],freeBlocks:c.freeBlocks,wrappers:[...b.wrappers],bombs:b.tuning.bombs,flags:b.tuning.flags,segments:[[0x424000,ShipSave.encode(c.memory.slice(0x424000,0x429280))],[b.game,ShipSave.encode(c.memory.slice(b.game,b.game+0x200))],[0x600000,ShipSave.encode(c.memory.slice(0x600000,c.heap))]]}));}
 static decode(bytes){let d;try{d=JSON.parse(new TextDecoder().decode(bytes));if(d.format!=='ship10-web'||d.version!==1||d.source!=='03756e0340b608bff99b889b351ff1d61397f4b62a3a830476845c59ed357d3b'||!Number.isFinite(d.step)||d.step<1||d.step>181||!Number.isInteger(d.heap)||d.heap<0x600000||d.heap>0xd00000)throw Error();ShipTuning.rules(d.rules);if(!['respawnSeconds','shieldSeconds'].includes(d.protectionKind))throw Error();const expected=[[0x424000,0x5280],[0x500000,0x200],[0x600000,d.heap-0x600000]];if(d.segments.length!==3)throw Error();d.segments=d.segments.map(([a,s],i)=>{const raw=Uint8Array.from(atob(s),x=>x.charCodeAt(0));if(a!==expected[i][0]||raw.length!==expected[i][1])throw Error();return [a,raw];});for(const pairs of [d.blocks,d.freeBlocks])for(const [a,n] of pairs)if(!Number.isInteger(a)||!Number.isInteger(n)||a<0x600000||n<0||a+n>d.heap)throw Error();if(d.rules.enabled&&(!Number.isInteger(d.bombs)||d.bombs<0x600000||d.bombs+5600>d.heap||!Number.isInteger(d.flags)||d.flags<0x600000||d.flags+400>d.heap))throw Error();}catch{throw Error('请选择本游戏导出的 .ship10 存档');}return d;}
 static restore(b,d){b.tuning.apply(d.rules);const c=b.cpu;for(const [a,bytes] of d.segments)c.memory.set(bytes,a);c.heap=d.heap;c.blocks=new Map(d.blocks);c.freeBlocks=d.freeBlocks;c.seed=d.seed;b.wrappers=new Map(d.wrappers);b.step=d.step;b.tuning.protectionKind=d.protectionKind;if(d.rules.enabled){b.tuning.bombs=d.bombs;b.tuning.flags=d.flags;}b.messages=[];b.notice='';c.suspended=false;b.pendingName=null;}
}
window.ShipSave=ShipSave;
